config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :categories
  resources :categorygroups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: 'listings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :categorygroup_id, presence: true
  belongs_to :categorygroup
end

app/models/categorygroup.rb
class Categorygroup < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :categories
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :icon, :description ])
    end
end

app/controllers/categorygroups_controller.rb
class CategorygroupsController < ApplicationController
  before_action :set_categorygroup, only: %i[ show edit update destroy ]

  # GET /categorygroups or /categorygroups.json
  def index
    @categorygroups = Categorygroup.all
  end

  # GET /categorygroups/1 or /categorygroups/1.json
  def show
  end

  # GET /categorygroups/new
  def new
    @categorygroup = Categorygroup.new
  end

  # GET /categorygroups/1/edit
  def edit
  end

  # POST /categorygroups or /categorygroups.json
  def create
    @categorygroup = Categorygroup.new(categorygroup_params)

    respond_to do |format|
      if @categorygroup.save
        format.html { redirect_to @categorygroup, notice: "Categorygroup was successfully created." }
        format.json { render :show, status: :created, location: @categorygroup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categorygroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorygroups/1 or /categorygroups/1.json
  def update
    respond_to do |format|
      if @categorygroup.update(categorygroup_params)
        format.html { redirect_to @categorygroup, notice: "Categorygroup was successfully updated." }
        format.json { render :show, status: :ok, location: @categorygroup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorygroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorygroups/1 or /categorygroups/1.json
  def destroy
    @categorygroup.destroy!

    respond_to do |format|
      format.html { redirect_to categorygroups_path, status: :see_other, notice: "Categorygroup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorygroup
      @categorygroup = Categorygroup.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def categorygroup_params
      params.expect(categorygroup: [ :name, :icon, :description ])
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy!

    respond_to do |format|
      format.html { redirect_to listings_path, status: :see_other, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.expect(listing: [ :name, :url, :logo, :description, :category_id, :address, :lat, :long ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorygroups_helper.rb
module CategorygroupsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/categorygroups/_categorygroup.html.erb
<div id="<%= dom_id categorygroup %>">
  <p>
    <strong>Name:</strong>
    <%= categorygroup.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= categorygroup.icon %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= categorygroup.description %>
  </p>

</div>

app/views/categorygroups/_form.html.erb
<%= form_with(model: categorygroup) do |form| %>
  <% if categorygroup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(categorygroup.errors.count, "error") %> prohibited this categorygroup from being saved:</h2>

      <ul>
        <% categorygroup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categorygroups/edit.html.erb
<% content_for :title, "Editing categorygroup" %>

<h1>Editing categorygroup</h1>

<%= render "form", categorygroup: @categorygroup %>

<br>

<div>
  <%= link_to "Show this categorygroup", @categorygroup %> |
  <%= link_to "Back to categorygroups", categorygroups_path %>
</div>

app/views/categorygroups/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categorygroups" %>

<h1>Categorygroups</h1>

<div id="categorygroups">
  <% @categorygroups.each do |categorygroup| %>
    <%= render categorygroup %>
    <p>
      <%= link_to "Show this categorygroup", categorygroup %>
    </p>
  <% end %>
</div>

<%= link_to "New categorygroup", new_categorygroup_path %>

app/views/categorygroups/new.html.erb
<% content_for :title, "New categorygroup" %>

<h1>New categorygroup</h1>

<%= render "form", categorygroup: @categorygroup %>

<br>

<div>
  <%= link_to "Back to categorygroups", categorygroups_path %>
</div>

app/views/categorygroups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @categorygroup %>

<div>
  <%= link_to "Edit this categorygroup", edit_categorygroup_path(@categorygroup) %> |
  <%= link_to "Back to categorygroups", categorygroups_path %>

  <%= button_to "Destroy this categorygroup", @categorygroup, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Riverina Online" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">   
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Oswald:wght@200..700&display=swap" rel="stylesheet">

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="header">
      <div class="branding">
        <img src="/icon.svg">
        <p class="branding1">let's get the</p>
        <p class="branding2">Riverina</p>
        <p class="branding3">Online</p>
      </div>
    </div>
    <%= yield %>
    <div id="footer">
      <div class="branding">
        <img src="/icon.svg">
        <p class="branding1">let's get the</p>
        <p class="branding2">Riverina</p>
        <p class="branding3">Online</p>
      </div>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :logo, style: "display: block" %>
    <%= form.text_field :logo %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :lat, style: "display: block" %>
    <%= form.text_field :lat %>
  </div>

  <div>
    <%= form.label :long, style: "display: block" %>
    <%= form.text_field :long %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Name:</strong>
    <%= listing.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= listing.url %>
  </p>

  <p>
    <strong>Logo:</strong>
    <%= listing.logo %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= listing.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= listing.category_id %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= listing.address %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= listing.lat %>
  </p>

  <p>
    <strong>Long:</strong>
    <%= listing.long %>
  </p>

</div>

app/views/listings/edit.html.erb
<% content_for :title, "Editing listing" %>

<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Listings" %>

<h1>Find a Business</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_listing_path %>

app/views/listings/new.html.erb
<% content_for :title, "New listing" %>

<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @listing %>

<div>
  <%= link_to "Edit this listing", edit_listing_path(@listing) %> |
  <%= link_to "Back to listings", listings_path %>

  <%= button_to "Destroy this listing", @listing, method: :delete %>
</div>